#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


case "$1" in
  attach)
    cmd='script /dev/null -qc "screen -r terraria"'
  ;;

  backup)
    echo "Backup $DIR/*.wld files"
    cmd="pushd "$DIR" ; mkdir -v -p backup && find . -maxdepth 1 -name '*.wld' -exec cp -v {} backup/{}.`date +%Y%m%d%H%M%S` \; ; popd"
  ;;
  
  *)
    send="`printf \"$*\r\"`"
    cmd="screen -S terraria -X stuff $send"
  ;;
esac


if [ "`stat -c '%u' /var/run/screen/S-terraria/`" = "$UID" ]
then
    echo "execute : $cmd"
    bash -c "$cmd"
else
    echo "execute as terraria : $cmd"
    su - terraria -c "$cmd"
fi

